### ISSUE TITLE
ansible usage

### ISSUE THREAD

**Issue by christopherreay** [christopherreay/ao-mini#5]
# Ansible Configuration Instructions

This guide explains how to configure your Ansible inventory file and `host_vars` to specify hosts along with variables like `sudo_user`, `sudo_user_pathToKeyFile`, `main_user`, and `main_user_pathToKeyFile`.

## Editing Inventory Host File

1. Open your Ansible inventory file (commonly named `inventory.ini` or just `inventory`).
2. Add your host, in this case `example.com`, under the appropriate group or directly in the file:

    ```ini
    [your_group_name]
    example.com ansible_ssh_host=your_server_ip ansible_ssh_user=your_ssh_username
    ```

   Replace `your_group_name`, `your_server_ip`, and `your_ssh_username` with the respective information for your environment.

## Adding host_vars for example.com

1. Create a new directory called `host_vars` if it does not already exist in the same location as your Ansible playbook.
2. Inside the `host_vars` directory, create a new YAML file with the name of your host, e.g., `example.com.yml`.
3. Open `example.com.yml` and add the following variables:

    ```yaml
    sudo_user: "your_unique_sudo_username"  # Example: "sudoeree5b73"
    sudo_user_pathToKeyFile: "path/to/sudo_user_key_file"  # Example: "~/.ssh/ansible.sudoUser.key.shouldCycleThisKey.pub"
    main_user: "your_main_username"  # Example: "aominiuser"
    main_user_pathToKeyFile: "path/to/main_user_key_file"  # Example: "~/.ssh/ansible.mainUser.key.shouldCycleThisKey.pub"
    ```

   Replace `your_unique_sudo_username`, `path/to/sudo_user_key_file`, `your_main_username`, and `path/to/main_user_key_file` with your specific values.

By following these steps, you will configure Ansible to connect to `example.com` and use the specified variables for user and SSH key management.
